### ISSUE TITLE
Not showing in IOS no errors too. but working on android.

### ISSUE THREAD

**Issue by castelar007** [timbru31/cordova-plugin-lottie-splashscreen#86] opened 2019-07-30 02:01 UTC
# Bug report
no erros
## Expected output
the animation
## What do you see instead?
nothing
## Version information

?xml version='1.0' encoding='utf-8'?>
widget id="io.beanar.ocho.life" version="0.0.27" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    name>Ocho/name>
    description>Ocho App/description>
    author email="be@beanar.io" href="https://www.facebook.com/beanar10/">Beanario Software Team/author>
    content src="index.html" />
    access origin="*" />
    allow-intent href="http://*/*" />
    allow-intent href="https://*/*" />
    allow-intent href="tel:*" />
    allow-intent href="sms:*" />
    allow-intent href="mailto:*" />
    allow-intent href="geo:*" />
    preference name="ScrollEnabled" value="false" />
    preference name="BackupWebStorage" value="none" />
    preference name="SplashMaintainAspectRatio" value="true" />
    preference name="FadeSplashScreenDuration" value="300" />
    preference name="SplashShowOnlyFirstTime" value="false" />
    preference name="SplashScreen" value="screen" />
    preference name="KeyboardDisplayRequiresUserAction" value="false" />
    preference name="SplashScreenDelay" value="100000" />
    preference name="ShowSplashScreen" value="true" />
    preference name="ShowSplashScreenSpinner" value="false" />
    preference name="LottieRemoteEnabled" value="true" />
    preference name="LottieAnimationLocation" value=""
    preference name="LottieBackgroundColor" value="#fa5103" />
    preference name="LottieFullScreen" value="true" />
    platform name="android">
        allow-intent href="market:*" />
        icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
        resource-file src="build-extras.gradle" target="app/build-extras.gradle" />
        resource-file src="resources/android/adaptiveicon/res/drawable/ic_launcher_background.xml" target="app/src/main/res/drawable/ic_launcher_background.xml" />
        resource-file src="resources/android/adaptiveicon/res/mipmap-hdpi/ic_launcher.png" target="app/src/main/res/mipmap-hdpi/ic_launcher.png" />
        resource-file src="resources/android/adaptiveicon/res/mipmap-hdpi/ic_launcher_round.png" target="app/src/main/res/mipmap-hdpi/ic_launcher_round.png" />
        resource-file src="resources/android/adaptiveicon/res/mipmap-mdpi/ic_launcher.png" target="app/src/main/res/mipmap-mdpi/ic_launcher.png" />
        resource-file src="resources/android/adaptiveicon/res/mipmap-mdpi/ic_launcher_round.png" target="app/src/main/res/mipmap-mdpi/ic_launcher_round.png" />
        resource-file src="resources/android/adaptiveicon/res/mipmap-xhdpi/ic_launcher.png" target="app/src/main/res/mipmap-xhdpi/ic_launcher.png" />
        resource-file src="resources/android/adaptiveicon/res/mipmap-xhdpi/ic_launcher_round.png" target="app/src/main/res/mipmap-xhdpi/ic_launcher_round.png" />
        resource-file src="resources/android/adaptiveicon/res/mipmap-xxhdpi/ic_launcher.png" target="app/src/main/res/mipmap-xxhdpi/ic_launcher.png" />
        resource-file src="resources/android/adaptiveicon/res/mipmap-xxhdpi/ic_launcher_round.png" target="app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png" />
        resource-file src="resources/android/adaptiveicon/res/mipmap-xxxhdpi/ic_launcher.png" target="app/src/main/res/mipmap-xxxhdpi/ic_launcher.png" />
        resource-file src="resources/android/adaptiveicon/res/mipmap-xxxhdpi/ic_launcher_round.png" target="app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png" />
        resource-file src="resources/android/icon/drawable-mdpi-icon.png" target="app/src/main/res/drawable-mdpi/icon.png" />
        resource-file src="resources/android/icon/drawable-hdpi-icon.png" target="app/src/main/res/drawable-hdpi/icon.png" />
        resource-file src="resources/android/icon/drawable-xhdpi-icon.png" target="app/src/main/res/drawable-xhdpi/icon.png" />
        resource-file src="resources/android/icon/drawable-xxhdpi-icon.png" target="app/src/main/res/drawable-xxhdpi/icon.png" />
        resource-file src="resources/android/icon/drawable-xxxhdpi-icon.png" target="app/src/main/res/drawable-xxxhdpi/icon.png" />
        replace-string file="project.properties" find="com.google.android.gms:play-services-auth:11.8.0" replace="com.google.android.gms:play-services-auth:+" />
        replace-string file="project.properties" find="com.google.android.gms:play-services-identity:11.8.0" replace="com.google.android.gms:play-services-identity:+" />
        replace-string file="project.properties" find="com.google.android.gms:play-services-tagmanager:+" replace="com.google.android.gms:play-services-tagmanager:16.0.8" />
        replace-string file="project.properties" find="com.google.firebase:firebase-core:+" replace="com.google.firebase:firebase-core:16.0.8" />
        replace-string file="project.properties" find="com.google.firebase:firebase-messaging:+" replace="com.google.firebase:firebase-messaging:17.6.0" />
        replace-string file="project.properties" find="com.google.firebase:firebase-config:+" replace="com.google.firebase:firebase-config:16.5.0" />
        replace-string file="project.properties" find="com.google.firebase:firebase-perf:+" replace="com.google.firebase:firebase-perf:16.2.5" />
        plugin name="cordova-plugin-androidx" spec="^1.0.2" />
        plugin name="cordova-plugin-androidx-adapter" spec="^1.0.2" />
    /platform>
    platform name="ios">
        edit-config file="*-Info.plist" mode="merge" target="NSCameraUsageDescription">
            string>Ocho necesita acceso a tu camara para tomar Fotos/string>
        /edit-config>
        edit-config file="*-Info.plist" mode="merge" target="NSPhotoLibraryUsageDescription">
            string>Ocho necesita acceso a tu librería de fotos para seleccionar una/string>
        /edit-config>
        edit-config file="*-Info.plist" mode="merge" target="NSLocationWhenInUseUsageDescription">
            string>Ocho necesita tu geo-posición para funcionar correctamente/string>
        /edit-config>
        edit-config file="*-Info.plist" mode="merge" target="NSLocationAlwaysUsageDescription">
            string>Ocho necesita tu geo-posición para funcionar correctamente/string>
        /edit-config>
        edit-config file="*-Info.plist" mode="merge" target="NSPhotoLibraryAddUsageDescription">
            string>Ocho necesita permiso para guardar fotos/string>
        /edit-config>
        preference name="KeyboardResize" value="false" />
        allow-intent href="itms:*" />
        allow-intent href="itms-apps:*" />
        icon height="57" src="resources/ios/icon/icon.png" width="57" />
        icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
        splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
        splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
    /platform>
    plugin name="cordova-plugin-advanced-http" spec="^2.0.8" />
    plugin name="cordova-plugin-statusbar" spec="git+https://github.com/apache/cordova-plugin-statusbar.git" />
    plugin name="cordova-plugin-ionic-keyboard" spec="^2.1.3" />
    plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    plugin name="cordova-plugin-device" spec="^2.0.2" />
    plugin name="cordova-plugin-splashscreen" spec="^5.0.2" />
    plugin name="cordova-plugin-ionic-webview" spec="^4.0.1">
        variable name="ANDROID_SUPPORT_ANNOTATIONS_VERSION" value="27.+" />
    /plugin>
    plugin name="com.telerik.plugins.nativepagetransitions" spec="^0.6.5" />
    plugin name="cordova-sqlite-storage" spec="^3.2.0" />
    plugin name="cordova-plugin-geolocation" spec="^4.0.1" />
    plugin name="cordova-plugin-sim" spec="^1.3.3" />
    plugin name="cordova-plugin-firebase" spec="2.0.5" />
    plugin name="cordova-fabric-plugin" spec="1.1.14-dev">
        variable name="FABRIC_API_KEY" value="" />
        variable name="FABRIC_API_SECRET" value="" />
    /plugin>
    plugin name="cordova-plugin-file" spec="6.0.1" />
    plugin name="cordova-plugin-platform-replace" spec="1.0.0" />
    plugin name="cordova-plugin-navigationbar-color" spec="0.0.8" />
    plugin name="ionic-plugin-deeplinks" spec="^1.0.20">
        variable name="URL_SCHEME" value="ocholife" />
        variable name="DEEPLINK_SCHEME" value="https" />
        variable name="DEEPLINK_HOST" value="beanar.io" />
        variable name="ANDROID_PATH_PREFIX" value="/" />
        variable name="ANDROID_2_PATH_PREFIX" value="/" />
        variable name="ANDROID_3_PATH_PREFIX" value="/" />
        variable name="ANDROID_4_PATH_PREFIX" value="/" />
        variable name="ANDROID_5_PATH_PREFIX" value="/" />
        variable name="DEEPLINK_2_SCHEME" value=" " />
        variable name="DEEPLINK_2_HOST" value=" " />
        variable name="DEEPLINK_3_SCHEME" value=" " />
        variable name="DEEPLINK_3_HOST" value=" " />
        variable name="DEEPLINK_4_SCHEME" value=" " />
        variable name="DEEPLINK_4_HOST" value=" " />
        variable name="DEEPLINK_5_SCHEME" value=" " />
        variable name="DEEPLINK_5_HOST" value=" " />
    /plugin>
    plugin name="cordova-plugin-facebook4" spec="5.0.0">
        variable name="APP_ID" value="" />
        variable name="APP_NAME" value="ocho" />
        variable name="FACEBOOK_HYBRID_APP_EVENTS" value="false" />
        variable name="FACEBOOK_ANDROID_SDK_VERSION" value="5.0.2" />
    /plugin>
    plugin name="cordova-plugin-googleplus" spec="^8.0.0">
        variable name="REVERSED_CLIENT_ID" value="6666625-" />
        variable name="PLAY_SERVICES_VERSION" value="11.8.0" />
    /plugin>
    plugin name="cordova-plugin-camera" spec="^4.1.0">
        variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
    /plugin>
    engine name="android" spec="^8.0.0" />
    engine name="ios" spec="^5.0.0" />
    plugin name="cordova-plugin-lottie-splashscreen" spec="^0.5.1" />
/widget>

Plugins: 

com.telerik.plugins.nativepagetransitions,cordova-fabric-plugin,cordova-plugin-add-swift-support,cordova-plugin-advanced-http,cordova-plugin-androidx,cordova-plugin-androidx-adapter,cordova-plugin-camera,cordova-plugin-device,cordova-plugin-facebook4,cordova-plugin-file,cordova-plugin-firebase,cordova-plugin-geolocation,cordova-plugin-googleplus,cordova-plugin-ionic-keyboard,cordova-plugin-ionic-webview,cordova-plugin-lottie-splashscreen,cordova-plugin-navigationbar-color,cordova-plugin-platform-replace,cordova-plugin-sim,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-whitelist,cordova-sqlite-storage,ionic-plugin-deeplinks

Error retrieving Android platform information: 
Android SDK is not set up properly. Make sure that the Android SDK 'tools' and 'platform-tools' directories are in the PATH variable. 

Error: android: Command failed with exit code ENOENT

iOS platform:

Xcode 10.2.1
Build version 10E1001
## Checklist

-   [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
-   [ ] I have added a valid version output
-   [ ] I have attached necessary information like a screenshot, example project or videos

**Comment by castelar007** [comment] 2019-07-30 04:01
UPDATE: seems to work if i setup lottie in the config.xml. but if i do it in the function .show it doesnt.

**Comment by timbru31** [comment] 2019-07-30 07:57
Without proper version information and a reproducible example I'm unable to help.

**Comment by timbru31** [comment] 2019-08-09 12:09
I see you edited some information, thanks. Cam you post the `show` command you are trying to use? @castelar007

**Comment by timbru31** [comment] 2019-08-15 12:10
Closing due to missing version information, and steps to re-produce. If the issue persists please open a new one and follow the issue template, thanks!

**Closed by timbru31** 2019-08-15 12:10 UTC
Labels: waiting for feedback
