### ISSUE TITLE
Is posible to disable caching in android?

### ISSUE THREAD

**Issue by castelar007** [timbru31/cordova-plugin-lottie-splashscreen#139] opened 2019-12-27 20:16 UTC
i had a firestore storage link with my data.json to have dinamic splash depending season. this aproach works perfect in ios, but android seems to caching the first data.json it loads. is there a way to disable this caching? and load the  data.json every time from firebase storage??

**Comment by timbru31** [comment] 2019-12-27 21:46
Thanks for the issue, I’ll see if there are any options to change the caching mechanism

**Comment by timbru31** [comment] 2019-12-28 14:33
This has been published as 0.8.0-beta.0.

**Comment by castelar007** [comment] 2019-12-30 15:48
thank you sir!!

**Comment by timbru31** [comment] 2020-01-03 19:38
Blocked by upstream: https://github.com/airbnb/lottie-android/issues/1289#issuecomment-570676043

**Comment by timbru31** [comment] 2020-02-04 12:57
I'm moving this to the 0.9.0 milestone because the issue is blocked by upstream. This unblocks the 0.8.0 RC

**Comment by timbru31** [comment] 2020-02-20 14:45
Good news, this has been fixed and will be included in the Lottie 3.3.2 release!

**Comment by castelar007** [comment] 2020-02-20 19:33
nice

**Closed** 2020-02-24 13:35 UTC
Labels: enhancement

**Comment by timbru31** [comment] 2020-04-08 21:14
Published in v0.8.1
