### ISSUE TITLE
App Crashes With Lottie Animation in Ionic Project

### ISSUE THREAD

**Issue by JacobHornbeck** [timbru31/cordova-plugin-lottie-splashscreen#520] opened 2023-02-19 02:54 UTC
# Bug report

**NOTE:** This is with Capacitor not Cordova. I am using [this video tutorial](https://www.youtube.com/watch?v=JfX7pBq1YG4), following what he does, but it isn't working.

## What steps will reproduce the problem?
Just followed the steps in the tutorial mentioned above, and I got this error

## Expected output
Lottie splash screen animation shows and then hides.

## What do you see instead?
App crashes on open.

## Log file of the issue/error
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.ionic.starter, PID: 11710
    java.lang.NullPointerException: Attempt to invoke interface method 'void org.apache.cordova.CordovaWebViewEngine.evaluateJavascript(java.lang.String, android.webkit.ValueCallback)' on a null object reference
        at de.dustplanet.cordova.lottie.LottieSplashScreen$addAnimationListeners$1.onAnimationStart(LottieSplashScreen.kt:284)
        at android.animation.Animator$AnimatorListener.onAnimationStart(Animator.java:538)
        at com.airbnb.lottie.utils.BaseLottieAnimator.notifyStart(BaseLottieAnimator.java:57)
        at com.airbnb.lottie.utils.LottieValueAnimator.playAnimation(LottieValueAnimator.java:207)
        at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:445)
        at com.airbnb.lottie.LottieDrawable$2.run(LottieDrawable.java:438)
        at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:229)
        at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:550)
        at de.dustplanet.cordova.lottie.LottieSplashScreen.createLottieComposition$lambda-3(LottieSplashScreen.kt:200)
        at de.dustplanet.cordova.lottie.LottieSplashScreen.$r8$lambda$Z5JPNbsIT5QwjkWf2fsGcnuDdsk(Unknown Source:0)
        at de.dustplanet.cordova.lottie.LottieSplashScreen$$ExternalSyntheticLambda1.onResult(Unknown Source:4)
        at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:144)
        at com.airbnb.lottie.LottieTask.access$100(LottieTask.java:27)
        at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:131)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:250)
        at android.app.ActivityThread.main(ActivityThread.java:7886)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:970)
```

## Version information
I don't believe this is applicable for my situation.

**Comment by timbru31** [comment] 2023-02-19 15:57
Duplicate of #486

**Closed by timbru31** 2023-02-19 15:57 UTC
